const CATALOGUE: &[(&str, &str)] = &[
    (
        "also copy records of Jobs that were executing when their processes ended; the restored service records them as lost",
        "auch Einträge von Jobs kopieren, die ausgeführt wurden, als ihre Prozesse endeten; der wiederhergestellte Dienst trägt sie als verloren ein",
    ),
    (
        "cannot write the output",
        "die Ausgabe lässt sich nicht schreiben",
    ),
    (
        "job - execute and schedule jobs",
        "job - Jobs ausführen und einplanen",
    ),
    (
        "Usage: job [OPTIONS] COMMAND [ARGS...]",
        "Aufruf: job [OPTIONEN] BEFEHL [ARGUMENTE...]",
    ),
    (
        "See 'job COMMAND --help' or 'man job'.",
        "Siehe 'job BEFEHL --help' oder 'man job'.",
    ),
    ("See 'man job'.", "Siehe 'man job'."),
    ("Execution", "Ausführung"),
    ("Interaction", "Interaktion"),
    ("Inspection", "Einsicht"),
    ("Organization", "Organisation"),
    ("Administration", "Verwaltung"),
    ("Earlier spellings", "Frühere Schreibweisen"),
    ("Service and tools", "Dienst und Werkzeuge"),
    (
        "(for Jobs started with --pty)",
        "(für Jobs, die mit --pty gestartet wurden)",
    ),
    ("Usage:", "Aufruf:"),
    ("Commands:", "Befehle:"),
    ("Earlier spellings:", "Frühere Schreibweisen:"),
    ("Operands:", "Operanden:"),
    ("Exit status:", "Rückgabewert:"),
    ("Exit status", "Rückgabewert"),
    ("Option", "Option"),
    ("Operand", "Operand"),
    ("Meaning", "Bedeutung"),
    ("job syntax reference", "Syntaxreferenz für job"),
    (
        "Generated by `job help --syntax` from the shared command definition. Change the definition, not this file.",
        "Erzeugt von `job help --syntax` aus der gemeinsamen Befehlsdefinition. Ändere die Definition, nicht diese Datei.",
    ),
    (
        "This command is defined by another part of job; its options are not listed here.",
        "Dieser Befehl wird von einem anderen Teil von job bereitgestellt; seine Optionen stehen hier nicht.",
    ),
    (
        "With --format json the envelope kind is",
        "Mit --format json lautet kind im Umschlag",
    ),
    (
        "--json prints the earlier JSON unchanged; --format json wraps the same data in the versioned envelope.",
        "--json gibt das bisherige JSON unverändert aus; --format json legt dieselben Daten in den versionierten Umschlag.",
    ),
    (
        "cannot collect the output for --format json",
        "die Ausgabe für --format json lässt sich nicht sammeln",
    ),
    ("there is no Queue `{word}`", "es gibt keine Queue `{word}`"),
    (
        "unknown command `{word}`; see job --help",
        "unbekannter Befehl `{word}`; siehe job --help",
    ),
    (
        "unknown option `{word}` for job {command}; see job {command} --help",
        "unbekannte Option `{word}` für job {command}; siehe job {command} --help",
    ),
    (
        "unknown option `{word}` for job {command}; it takes {options}; see job {command} --help",
        "unbekannte Option `{word}` für job {command}; möglich sind {options}; siehe job {command} --help",
    ),
    (
        "option `{word}` of job {command} needs a value; see job {command} --help",
        "Option `{word}` von job {command} braucht einen Wert; siehe job {command} --help",
    ),
    (
        "job {command} takes no `{word}`; see job {command} --help",
        "job {command} nimmt kein `{word}`; siehe job {command} --help",
    ),
    (
        "`{word}` is not an output format of job {command}; write text or json",
        "`{word}` ist kein Ausgabeformat von job {command}; schreibe text oder json",
    ),
    (
        "job {command} takes exactly one ID; see job {command} --help",
        "job {command} nimmt genau eine ID; siehe job {command} --help",
    ),
    (
        "job {command} takes no operand `{word}`; see job {command} --help",
        "job {command} nimmt keinen Operanden `{word}`; siehe job {command} --help",
    ),
    (
        "job {command} cannot read `{word}`; see job {command} --help",
        "job {command} kann `{word}` nicht lesen; siehe job {command} --help",
    ),
    (
        "A waiting client that ends does not cancel the Job.",
        "Endet ein wartender Client, wird der Job nicht abgebrochen.",
    ),
    ("Admission", "Zulassung"),
    (
        "Arguments after -- execute literally; use --shell SHELL or an explicit sh -c command for shell syntax.",
        "Argumente nach -- werden wörtlich ausgeführt; für Shell-Syntax nimm --shell SHELL oder einen ausdrücklichen Befehl mit sh -c.",
    ),
    (
        "BFQ weight on one block device",
        "BFQ-Gewicht auf einem Blockgerät",
    ),
    ("CPU time limit in CPUs", "Grenze der CPU-Zeit in CPUs"),
    (
        "CPU weight from 1 through 10000",
        "CPU-Gewicht von 1 bis 10000",
    ),
    (
        "CPUs counted at admission",
        "CPUs, die bei der Zulassung zählen",
    ),
    (
        "CPUs the processes may run on",
        "CPUs, auf denen die Prozesse laufen dürfen",
    ),
    (
        "Completed Jobs are not listed; ask for one with job show ID.",
        "Beendete Jobs werden nicht aufgelistet; frage einen mit job show ID ab.",
    ),
    (
        "Controls for the whole subtree",
        "Steuerung für den ganzen Teilbaum",
    ),
    ("Defaults for each Job", "Standardwerte für jeden Job"),
    ("Earlier Queue settings", "Frühere Queue-Einstellungen"),
    (
        "I/O rate limits of one block device",
        "E/A-Ratengrenzen eines Blockgeräts",
    ),
    (
        "I/O weight on one block device",
        "E/A-Gewicht auf einem Blockgerät",
    ),
    ("NUMA memory policy", "NUMA-Speicherrichtlinie"),
    ("Options", "Optionen"),
    ("Placement and network", "Ort und Netzwerk"),
    (
        "Pressure describes affected work, not the cause of contention.",
        "Druck beschreibt die betroffene Arbeit, nicht die Ursache der Konkurrenz.",
    ),
    (
        "Preview with --dry-run. Exit 75 means pending: ask with resource-update instead of sending the change again.",
        "Sieh dir die Änderung mit --dry-run vorher an. Rückgabewert 75 heißt ausstehend: frage mit resource-update nach, statt die Änderung erneut zu senden.",
    ),
    (
        "Process and security controls",
        "Prozess- und Sicherheitssteuerung",
    ),
    ("Reservation", "Reservierung"),
    ("Resource controls", "Ressourcensteuerung"),
    ("a command of job", "ein Befehl von job"),
    ("a configuration file", "eine Konfigurationsdatei"),
    ("a kernel pressure file", "eine Druckdatei des Kernels"),
    (
        "a monitor by name, left, right, primary or number",
        "ein Monitor nach Name, left, right, primary oder Nummer",
    ),
    ("a preset revision", "eine Revision einer Voreinstellung"),
    ("a recorded pressure file", "eine aufgezeichnete Druckdatei"),
    (
        "a setting by its option name without dashes",
        "eine Einstellung mit ihrem Optionsnamen ohne Striche",
    ),
    (
        "a versioned execution profile",
        "ein versioniertes Ausführungsprofil",
    ),
    (
        "a versioned scheduling class",
        "eine versionierte Planungsklasse",
    ),
    (
        "answer one JSON question about a command line: allow, deny or rewrite",
        "eine JSON-Frage zu einer Befehlszeile beantworten: erlauben, ablehnen oder umschreiben",
    ),
    (
        "accept Jobs whose execution state is unknown",
        "Jobs annehmen, deren Ausführungszustand unbekannt ist",
    ),
    (
        "accept new submissions again",
        "neue Einreichungen wieder annehmen",
    ),
    (
        "admission priority from -1000 through 1000",
        "Zulassungspriorität von -1000 bis 1000",
    ),
    (
        "aging interval for waiting Jobs",
        "Alterungsintervall für wartende Jobs",
    ),
    (
        "all its Jobs together, each way",
        "alle ihre Jobs zusammen, je Richtung",
    ),
    (
        "all, stdout, stderr, combined or diagnostic",
        "all, stdout, stderr, combined oder diagnostic",
    ),
    (
        "allow lowering memory.max; processes may be killed",
        "memory.max senken erlauben; Prozesse können beendet werden",
    ),
    (
        "also allow writing under PATH; implies --confine",
        "auch Schreiben unter PATH erlauben; schließt --confine ein",
    ),
    (
        "always, with no output on any error",
        "immer, bei jedem Fehler ohne Ausgabe",
    ),
    (
        "an exclusive device to hold",
        "ein Gerät, das der Job allein hält",
    ),
    ("an ssh option used with --on", "eine ssh-Option für --on"),
    (
        "ask the job service of another host over ssh",
        "den job-Dienst eines anderen Hosts über ssh fragen",
    ),
    ("bash, fish or zsh", "bash, fish oder zsh"),
    ("bytes it may write", "Bytes, die er schreiben darf"),
    ("cancel a Job", "einen Job abbrechen"),
    (
        "cancel every Job below the path",
        "jeden Job unter dem Pfad abbrechen",
    ),
    (
        "cancel every Job waiting in a Queue",
        "jeden wartenden Job einer Queue abbrechen",
    ),
    (
        "namespaces created for the processes",
        "Namensräume, die für die Prozesse angelegt werden",
    ),
    (
        "make the file system tree read-only",
        "den Dateibaum schreibgeschützt machen",
    ),
    (
        "give the processes their own empty temporary directories",
        "den Prozessen eigene, leere temporäre Verzeichnisse geben",
    ),
    (
        "paths that stay writable under a read-only root",
        "Pfade, die unter einem schreibgeschützten Dateibaum beschreibbar bleiben",
    ),
    (
        "bytes kept from the start of each output stream",
        "Bytes, die vom Anfang jedes Ausgabestroms behalten werden",
    ),
    (
        "bytes kept from the end of each output stream",
        "Bytes, die vom Ende jedes Ausgabestroms behalten werden",
    ),
    (
        "the key that, followed by d, leaves the terminal",
        "die Taste, mit der du, gefolgt von d, das Terminal verlässt",
    ),
    (
        "Detach with the detach key, Ctrl-] unless set otherwise, then d; the Job goes on.",
        "Trenne dich mit der Trenntaste, Strg-] wenn nichts anderes eingestellt ist, und dann d; der Job läuft weiter.",
    ),
    (
        "a private file with user:password for the proxy",
        "eine private Datei mit user:password für den Proxy",
    ),
    (
        "only records about this Job, Queue or Group",
        "nur Einträge zu diesem Job, dieser Queue oder Gruppe",
    ),
    ("only records of this action", "nur Einträge dieser Aktion"),
    (
        "only records from this Unix time in milliseconds on",
        "nur Einträge ab dieser Unix-Zeit in Millisekunden",
    ),
    (
        "a repeated submission with this key returns the first Job",
        "eine wiederholte Einreichung mit diesem Schlüssel liefert den ersten Job",
    ),
    (
        "capabilities removed before exec",
        "Capabilities, die vor exec entfernt werden",
    ),
    (
        "capture the window of this Job",
        "das Fenster dieses Jobs aufnehmen",
    ),
    (
        "capture the window of this process and its children",
        "das Fenster dieses Prozesses und seiner Kinder aufnehmen",
    ),
    (
        "change resource controls of a running Job",
        "Ressourcensteuerung eines laufenden Jobs ändern",
    ),
    (
        "change resource controls of an existing subtree",
        "Ressourcensteuerung eines bestehenden Teilbaums ändern",
    ),
    (
        "change the admission priority of a waiting Job",
        "die Zulassungspriorität eines wartenden Jobs ändern",
    ),
    (
        "check the installation and say what is missing",
        "die Installation prüfen und sagen, was fehlt",
    ),
    (
        "check, create, show or reload the service configuration",
        "die Dienstkonfiguration prüfen, anlegen, zeigen oder neu laden",
    ),
    (
        "configure a WireGuard interface inside a namespace",
        "eine WireGuard-Schnittstelle in einem Namensraum einrichten",
    ),
    (
        "copy PATH back from the other host after the end",
        "PATH nach dem Ende vom anderen Host zurückkopieren",
    ),
    (
        "copy PATH to the other host before the start",
        "PATH vor dem Start auf den anderen Host kopieren",
    ),
    (
        "cores its Jobs hold together at most",
        "Kerne, die ihre Jobs zusammen höchstens halten",
    ),
    (
        "cores left to this host while one of its Jobs runs",
        "Kerne, die diesem Host bleiben, solange einer ihrer Jobs läuft",
    ),
    ("cores to reserve", "Kerne, die reserviert werden"),
    (
        "create a configuration file",
        "eine Konfigurationsdatei anlegen",
    ),
    (
        "create a verified backup of offline state",
        "eine geprüfte Sicherung des ruhenden Zustands anlegen",
    ),
    (
        "create an object without settings of its own",
        "ein Objekt ohne eigene Einstellungen anlegen",
    ),
    (
        "create held work without starting it",
        "angehaltene Arbeit anlegen, ohne sie zu starten",
    ),
    ("create the attempt held", "den Versuch angehalten anlegen"),
    (
        "each of its Jobs unless a Job says --bandwidth",
        "jeder ihrer Jobs, sofern ein Job nicht --bandwidth angibt",
    ),
    (
        "earlier spelling of --max-running",
        "frühere Schreibweise von --max-running",
    ),
    (
        "earlier spelling of queue create",
        "frühere Schreibweise von queue create",
    ),
    (
        "earlier spelling of queue remove",
        "frühere Schreibweise von queue remove",
    ),
    ("earlier spelling of show", "frühere Schreibweise von show"),
    (
        "errors, grep TEXT, lines A..B, tail N or full",
        "errors, grep TEXT, lines A..B, tail N oder full",
    ),
    (
        "evaluate pressure rules against a recorded file",
        "Druckregeln an einer aufgezeichneten Datei auswerten",
    ),
    (
        "execute a command and wait for it",
        "einen Befehl ausführen und auf ihn warten",
    ),
    (
        "explain why a Job waits and when it may start",
        "erklären, warum ein Job wartet und wann er starten kann",
    ),
    (
        "fair share between the children of a Group",
        "fairer Anteil zwischen den Kindern einer Gruppe",
    ),
    (
        "forbid gaining privileges through exec",
        "Rechtegewinn durch exec verbieten",
    ),
    (
        "freeze every running Job below the path",
        "jeden laufenden Job unter dem Pfad einfrieren",
    ),
    (
        "freeze the processes of a running Job",
        "die Prozesse eines laufenden Jobs einfrieren",
    ),
    (
        "give the Job a persistent shared terminal",
        "dem Job ein dauerhaftes gemeinsames Terminal geben",
    ),
    (
        "give up the pending operation",
        "den ausstehenden Vorgang aufgeben",
    ),
    ("hard memory limit", "harte Speichergrenze"),
    (
        "highest priority a Job may ask for",
        "höchste Priorität, die ein Job verlangen darf",
    ),
    (
        "hold the waiting Jobs below a Group",
        "die wartenden Jobs unter einer Gruppe anhalten",
    ),
    (
        "hold the waiting Jobs of a Queue",
        "die wartenden Jobs einer Queue anhalten",
    ),
    (
        "how long run waits before it returns 75",
        "wie lange run wartet, bevor es 75 zurückgibt",
    ),
    (
        "how long to wait, for example 30s",
        "wie lange gewartet wird, zum Beispiel 30s",
    ),
    (
        "how many of its Jobs run at once",
        "wie viele ihrer Jobs gleichzeitig laufen",
    ),
    (
        "include everything below the path",
        "alles unter dem Pfad einschließen",
    ),
    (
        "read or follow the record of state changes of Jobs, Queues and Groups",
        "das Protokoll der Zustandswechsel von Jobs, Queues und Gruppen lesen oder verfolgen",
    ),
    (
        "keep printing new records until interrupted",
        "neue Einträge ausgeben, bis du abbrichst",
    ),
    ("only records about this Job", "nur Einträge zu diesem Job"),
    (
        "only records about this Queue or Group and what lies below it",
        "nur Einträge zu dieser Queue oder Gruppe und allem darunter",
    ),
    (
        "text, or json for one JSON object per line",
        "text, oder json für ein JSON-Objekt je Zeile",
    ),
    (
        "Each record is one transition; a Job put back into its Queue is written as requeued.",
        "Jeder Eintrag ist ein Wechsel; ein Job, der zurück in seine Queue kommt, steht als requeued da.",
    ),
    (
        "read the record of requests that changed something",
        "das Protokoll der Anfragen lesen, die etwas verändert haben",
    ),
    (
        "join the shared terminal of a Job started with --pty",
        "dem gemeinsamen Terminal eines mit --pty gestarteten Jobs beitreten",
    ),
    (
        "json prints one versioned envelope with schema_version, kind and data",
        "json gibt einen versionierten Umschlag mit schema_version, kind und data aus",
    ),
    (
        "keep printing until the Job ends",
        "weiter ausgeben, bis der Job endet",
    ),
    (
        "let Bash interpret a single argument, as before",
        "ein einzelnes Argument wie früher von Bash deuten lassen",
    ),
    (
        "let a suspended Job run again",
        "einen angehaltenen Job wieder laufen lassen",
    ),
    (
        "let every suspended Job below the path run again",
        "jeden angehaltenen Job unter dem Pfad wieder laufen lassen",
    ),
    (
        "let small Jobs start ahead without delaying others",
        "kleine Jobs vorziehen, ohne andere zu verzögern",
    ),
    (
        "let the Job write only in its own tree",
        "den Job nur in seinem eigenen Baum schreiben lassen",
    ),
    (
        "let the waiting Jobs below a Group start again",
        "die wartenden Jobs unter einer Gruppe wieder starten lassen",
    ),
    (
        "let the waiting Jobs of a Queue start again",
        "die wartenden Jobs einer Queue wieder starten lassen",
    ),
    (
        "list every execution attempt of a Job",
        "jeden Ausführungsversuch eines Jobs auflisten",
    ),
    (
        "list every execution profile revision",
        "jede Revision der Ausführungsprofile auflisten",
    ),
    (
        "list every scheduling class revision",
        "jede Revision der Planungsklassen auflisten",
    ),
    (
        "list held, queued and running Jobs",
        "angehaltene, wartende und laufende Jobs auflisten",
    ),
    (
        "list or show versioned execution profiles",
        "versionierte Ausführungsprofile auflisten oder zeigen",
    ),
    (
        "list or show versioned scheduling classes",
        "versionierte Planungsklassen auflisten oder zeigen",
    ),
    (
        "list the objects of this kind",
        "die Objekte dieser Art auflisten",
    ),
    (
        "lowest priority a Job may ask for",
        "niedrigste Priorität, die ein Job verlangen darf",
    ),
    (
        "memory counted at admission",
        "Speicher, der bei der Zulassung zählt",
    ),
    (
        "memory its Jobs hold together at most",
        "Speicher, den ihre Jobs zusammen höchstens halten",
    ),
    (
        "memory throttling threshold",
        "Schwelle, ab der Speicher gedrosselt wird",
    ),
    (
        "memory to reserve, for example 4G",
        "Speicher, der reserviert wird, zum Beispiel 4G",
    ),
    (
        "migrate offline state into a new directory",
        "ruhenden Zustand in ein neues Verzeichnis migrieren",
    ),
    (
        "move an inactive object into another Group",
        "ein inaktives Objekt in eine andere Gruppe verschieben",
    ),
    (
        "network rate each way, for example 5Mbit",
        "Netzwerkrate je Richtung, zum Beispiel 5Mbit",
    ),
    (
        "one resource limit of the processes",
        "eine Ressourcengrenze der Prozesse",
    ),
    (
        "only lines containing TEXT",
        "nur Zeilen, die TEXT enthalten",
    ),
    (
        "only records from this Unix time in milliseconds",
        "nur Einträge ab dieser Unix-Zeit in Millisekunden",
    ),
    (
        "only records up to this Unix time in milliseconds",
        "nur Einträge bis zu dieser Unix-Zeit in Millisekunden",
    ),
    (
        "organize Groups of Groups and Queues",
        "Gruppen aus Gruppen und Queues ordnen",
    ),
    (
        "organize Queues; without a subcommand, show every Queue and its Jobs",
        "Queues ordnen; ohne Unterbefehl jede Queue und ihre Jobs zeigen",
    ),
    (
        "pressure rules as a JSON file",
        "Druckregeln als JSON-Datei",
    ),
    (
        "print a completion script for a shell",
        "ein Vervollständigungsskript für eine Shell ausgeben",
    ),
    (
        "print bytes unchanged, terminal controls included",
        "Bytes unverändert ausgeben, Terminalsteuerung eingeschlossen",
    ),
    (
        "print completion candidates for a shell",
        "Kandidaten für die Vervollständigung einer Shell ausgeben",
    ),
    (
        "print one JSON object per record",
        "ein JSON-Objekt je Eintrag ausgeben",
    ),
    (
        "print or follow the retained output of a Job",
        "die aufbewahrte Ausgabe eines Jobs ausgeben oder ihr folgen",
    ),
    (
        "print the final diagnostic summary instead of live output",
        "statt der laufenden Ausgabe die abschließende Diagnosezusammenfassung ausgeben",
    ),
    (
        "print the long text of every part",
        "den langen Text aller Teile ausgeben",
    ),
    ("print the result as JSON", "das Ergebnis als JSON ausgeben"),
    (
        "print the syntax reference as Markdown",
        "die Syntaxreferenz als Markdown ausgeben",
    ),
    (
        "print the policy file in use and its rules, and read no commands",
        "die verwendete Richtliniendatei und ihre Regeln ausgeben und keine Befehle lesen",
    ),
    (
        "print the verdict of the command policy for each line on standard input",
        "für jede Zeile der Standardeingabe das Urteil der Befehlsrichtlinie ausgeben",
    ),
    (
        "print the verdict of the hook for each command line on standard input",
        "für jede Befehlszeile der Standardeingabe das Urteil des Hooks ausgeben",
    ),
    (
        "processes and threads it may have",
        "Prozesse und Threads, die er haben darf",
    ),
    (
        "query the recorded log of a Job",
        "das aufgezeichnete Protokoll eines Jobs abfragen",
    ),
    (
        "read one kernel pressure file",
        "eine Druckdatei des Kernels lesen",
    ),
    ("refuse new submissions", "neue Einreichungen ablehnen"),
    (
        "release held work for scheduling",
        "angehaltene Arbeit zur Einplanung freigeben",
    ),
    (
        "reload the same profile while the service is drained",
        "dasselbe Profil neu laden, während der Dienst leer ist",
    ),
    (
        "remove an object and the records of its completed Jobs",
        "ein Objekt und die Einträge seiner beendeten Jobs entfernen",
    ),
    (
        "remove local settings so that inheritance applies again",
        "eigene Einstellungen entfernen, damit die Vererbung wieder gilt",
    ),
    (
        "remove the record of a completed Job",
        "den Eintrag eines beendeten Jobs entfernen",
    ),
    (
        "rename an object without changing its identity",
        "ein Objekt umbenennen, ohne seine Identität zu ändern",
    ),
    (
        "replace the command and environment of held or queued work",
        "Befehl und Umgebung angehaltener oder wartender Arbeit ersetzen",
    ),
    (
        "restore a backup into a new directory",
        "eine Sicherung in ein neues Verzeichnis zurückspielen",
    ),
    (
        "run SHELL -c with the first argument as the script",
        "SHELL -c mit dem ersten Argument als Skript ausführen",
    ),
    (
        "run on the job service of another host over ssh",
        "auf dem job-Dienst eines anderen Hosts über ssh ausführen",
    ),
    (
        "run the service for this host",
        "den Dienst für diesen Host ausführen",
    ),
    (
        "send a signal to the processes of a Job",
        "den Prozessen eines Jobs ein Signal senden",
    ),
    (
        "serve a request of another host over ssh",
        "eine Anfrage eines anderen Hosts über ssh bedienen",
    ),
    (
        "service failure, lost Job, start error or usage error",
        "Dienstfehler, verlorener Job, Startfehler oder Aufruffehler",
    ),
    (
        "set local defaults and constraints",
        "eigene Standardwerte und Beschränkungen setzen",
    ),
    (
        "show an object with its effective configuration",
        "ein Objekt mit seiner wirksamen Konfiguration zeigen",
    ),
    (
        "show help for job or for one command",
        "Hilfe zu job oder zu einem Befehl zeigen",
    ),
    (
        "show one execution profile revision",
        "eine Revision eines Ausführungsprofils zeigen",
    ),
    (
        "show one scheduling class revision",
        "eine Revision einer Planungsklasse zeigen",
    ),
    (
        "show or abandon a pending resource update",
        "eine ausstehende Ressourcenänderung zeigen oder aufgeben",
    ),
    (
        "show recorded pressure events",
        "aufgezeichnete Druckereignisse zeigen",
    ),
    (
        "show resource pressure of the host or of one Job",
        "den Ressourcendruck des Hosts oder eines Jobs zeigen",
    ),
    (
        "show the answer of a Job, or where it stands",
        "die Antwort eines Jobs zeigen oder wo er steht",
    ),
    (
        "show the effective service policy and its source",
        "die wirksame Dienstrichtlinie und ihre Quelle zeigen",
    ),
    (
        "show the resources, devices and Queues of a host",
        "Ressourcen, Geräte und Queues eines Hosts zeigen",
    ),
    (
        "print the service's metrics in the Prometheus text format",
        "die Metriken des Dienstes im Textformat von Prometheus ausgeben",
    ),
    (
        "When the service does not answer, job_up 0 is printed and the exit status is 125.",
        "Antwortet der Dienst nicht, wird job_up 0 ausgegeben und der Rückgabewert ist 125.",
    ),
    (
        "The service can also serve them over HTTP; see the [metrics] table in job.conf(5).",
        "Der Dienst kann sie auch über HTTP anbieten; siehe die Tabelle [metrics] in job.conf(5).",
    ),
    (
        "show the state of the pressure rules",
        "den Zustand der Druckregeln zeigen",
    ),
    ("show this help", "diese Hilfe zeigen"),
    (
        "show what would happen and change nothing",
        "zeigen, was geschähe, und nichts ändern",
    ),
    (
        "start Jobs strictly in submission order",
        "Jobs streng in der Reihenfolge der Einreichung starten",
    ),
    (
        "start a new attempt of a completed Job",
        "einen neuen Versuch eines beendeten Jobs starten",
    ),
    (
        "stop the Job after this long",
        "den Job nach dieser Dauer stoppen",
    ),
    (
        "submit a command and print the Job ID",
        "einen Befehl einreichen und die Job-ID ausgeben",
    ),
    ("success", "Erfolg"),
    (
        "supervise one Job for the service",
        "einen Job für den Dienst beaufsichtigen",
    ),
    ("swap limit", "Swap-Grenze"),
    (
        "system calls refused with an error",
        "Systemaufrufe, die mit einem Fehler abgelehnt werden",
    ),
    (
        "take no new Jobs and remove the Queue once it is empty",
        "keine neuen Jobs annehmen und die Queue entfernen, sobald sie leer ist",
    ),
    (
        "the Group that contains the object",
        "die Gruppe, die das Objekt enthält",
    ),
    (
        "the Job is still pending or running",
        "der Job wartet oder läuft noch",
    ),
    ("the Job succeeded", "der Job war erfolgreich"),
    (
        "the Job succeeded or the client detached",
        "der Job war erfolgreich oder der Client hat sich getrennt",
    ),
    (
        "the Job was cancelled or stopped by the service",
        "der Job wurde abgebrochen oder vom Dienst gestoppt",
    ),
    ("the Queue to use", "die Queue, die verwendet wird"),
    ("the X display to use", "das X-Display, das verwendet wird"),
    (
        "the attempt instead of the current one",
        "dieser Versuch statt des aktuellen",
    ),
    ("the change is still pending", "die Änderung steht noch aus"),
    (
        "the deadline passed while the Job was pending or running, or the service stayed unavailable",
        "die Frist lief ab, während der Job wartete oder lief, oder der Dienst blieb unerreichbar",
    ),
    (
        "the exit status of the Job itself; 128+S when signal S ended it",
        "der Rückgabewert des Jobs selbst; 128+S, wenn Signal S ihn beendet hat",
    ),
    (
        "the exit status of the completed Job",
        "der Rückgabewert des beendeten Jobs",
    ),
    (
        "the file is the host-wide one",
        "die Datei ist die des ganzen Hosts",
    ),
    ("the file to write", "die Datei, die geschrieben wird"),
    (
        "the host network, none, a proxy or tunnel, a configured namespace or a named profile",
        "das Netzwerk des Hosts, keines, ein Proxy oder Tunnel, ein konfigurierter Namespace oder ein benanntes Profil",
    ),
    (
        "show the network namespaces and profiles the service configuration names",
        "die Netzwerk-Namespaces und -Profile zeigen, die die Dienstkonfiguration nennt",
    ),
    (
        "list the configured network namespaces and profiles",
        "die konfigurierten Netzwerk-Namespaces und -Profile auflisten",
    ),
    (
        "show one network namespace or profile with its rules",
        "einen Netzwerk-Namespace oder ein Netzwerkprofil mit seinen Regeln zeigen",
    ),
    (
        "a name from the service configuration, or ns:NAME or profile:NAME",
        "ein Name aus der Dienstkonfiguration, oder ns:NAME oder profile:NAME",
    ),
    (
        "the label of the calling session",
        "das Etikett der aufrufenden Sitzung",
    ),
    (
        "the monitor its windows belong on",
        "der Monitor, auf den seine Fenster gehören",
    ),
    ("the name of a Queue", "der Name einer Queue"),
    ("the name of the caller", "der Name des Aufrufers"),
    (
        "the new directory to write",
        "das neue Verzeichnis, das geschrieben wird",
    ),
    ("the new name", "der neue Name"),
    ("the number of a Job", "die Nummer eines Jobs"),
    (
        "the operation ID printed by update",
        "die Vorgangs-ID, die update ausgegeben hat",
    ),
    (
        "the path of a Queue or Group",
        "der Pfad einer Queue oder Gruppe",
    ),
    (
        "the request was refused or a member failed",
        "die Anfrage wurde abgelehnt oder ein Mitglied ist gescheitert",
    ),
    (
        "the resource the file describes",
        "die Ressource, die die Datei beschreibt",
    ),
    ("the service profile", "das Dienstprofil"),
    (
        "the signal by name or number; TERM when absent",
        "das Signal als Name oder Nummer; ohne Angabe TERM",
    ),
    ("the ssh key used with --on", "der ssh-Schlüssel für --on"),
    (
        "the state directory to read",
        "das Zustandsverzeichnis, das gelesen wird",
    ),
    (
        "the word being completed",
        "das Wort, das vervollständigt wird",
    ),
    ("the working directory", "das Arbeitsverzeichnis"),
    (
        "usage error or service failure",
        "Aufruffehler oder Dienstfehler",
    ),
    (
        "use the environment of this shell instead of the saved one",
        "die Umgebung dieser Shell statt der gespeicherten verwenden",
    ),
    (
        "validate a configuration file",
        "eine Konfigurationsdatei prüfen",
    ),
    (
        "validate offline state and report migration readiness",
        "ruhenden Zustand prüfen und melden, ob er migriert werden kann",
    ),
    (
        "validate, back up, migrate or restore offline state",
        "ruhenden Zustand prüfen, sichern, migrieren oder zurückspielen",
    ),
    (
        "wait quietly for a Job and return its outcome",
        "still auf einen Job warten und sein Ergebnis zurückgeben",
    ),
    (
        "weight of this child from 1 through 10000",
        "Gewicht dieses Kindes von 1 bis 10000",
    ),
    ("Global options", "Globale Optionen"),
    (
        "use the system service, as JOB_SYSTEM=1 does",
        "den Systemdienst verwenden, wie JOB_SYSTEM=1",
    ),
    (
        "Written before the command, as in `job --system status 7`.",
        "Steht vor dem Befehl, wie in `job --system status 7`.",
    ),
    ("what to complete", "was vervollständigt wird"),
    (
        "where its Jobs run unless a Job says --dir",
        "wo ihre Jobs laufen, sofern ein Job nicht --dir angibt",
    ),
    (
        "where the verified backup goes",
        "wohin die geprüfte Sicherung kommt",
    ),
    (
        "write a PNG of a monitor or of the window of a Job",
        "ein PNG eines Monitors oder des Fensters eines Jobs schreiben",
    ),
    (
        "json prints one versioned envelope; tsv prints tab-separated columns under a header line",
        "json gibt einen versionierten Umschlag aus; tsv gibt tabulatorgetrennte Spalten unter einer Kopfzeile aus",
    ),
    (
        "only entries that carry this label; repeat to require several",
        "nur Einträge mit diesem Label; wiederhole die Option, um mehrere zu verlangen",
    ),
    (
        "list Jobs; held, queued and running ones unless asked otherwise",
        "Jobs auflisten; gehaltene, wartende und laufende, sofern nichts anderes verlangt ist",
    ),
    ("include completed Jobs", "beendete Jobs einschließen"),
    ("only Jobs in these states", "nur Jobs in diesen Zuständen"),
    (
        "list at most N Jobs, the most recent ones; 200 when absent",
        "höchstens N Jobs auflisten, die neuesten; ohne Angabe 200",
    ),
    (
        "With --all, --state, --label, --limit, --id or --format tsv the listing is a table with one line per Job.",
        "Mit --all, --state, --label, --limit, --id oder --format tsv ist die Liste eine Tabelle mit einer Zeile je Job.",
    ),
    (
        "The tsv columns are id, attempt, state, queue, session, priority, submitted_ms, started_ms, finished_ms, exit_status, labels and command; labels and command are JSON.",
        "Die tsv-Spalten sind id, attempt, state, queue, session, priority, submitted_ms, started_ms, finished_ms, exit_status, labels und command; labels und command sind JSON.",
    ),
    (
        "move a held or queued Job into another Queue",
        "einen gehaltenen oder wartenden Job in eine andere Queue verschieben",
    ),
    (
        "The Job keeps its number, its submission time and its waiting credit. The destination must exist and be open, and its constraints and priority bounds are checked again.",
        "Der Job behält seine Nummer, seine Einreichungszeit und sein Warteguthaben. Das Ziel muss vorhanden und offen sein, und seine Grenzen und Prioritätsschranken werden erneut geprüft.",
    ),
    (
        "The tsv columns are id, path, kind, paused, closed and labels; labels is JSON.",
        "Die tsv-Spalten sind id, path, kind, paused, closed und labels; labels ist JSON.",
    ),
    (
        "`{word}` is not an output format of job {command}; write text, json or tsv",
        "`{word}` ist kein Ausgabeformat von job {command}; schreibe text, json oder tsv",
    ),
    (
        "job {command} takes one ID and --queue PATH; see job {command} --help",
        "job {command} braucht eine ID und --queue PATH; siehe job {command} --help",
    ),
    (
        "a label for classification; it never affects scheduling or policy",
        "ein Label zur Einordnung; es beeinflusst weder Einplanung noch Regeln",
    ),
    (
        "Write label-KEY to remove one label and labels to remove all of them.",
        "Schreibe label-KEY, um ein Label zu entfernen, und labels, um alle zu entfernen.",
    ),
    (
        "what the first SIGINT or SIGTERM does: pass it to the Job, leave the Job running, or cancel it",
        "was das erste SIGINT oder SIGTERM bewirkt: an den Job weitergeben, den Job weiterlaufen lassen oder ihn abbrechen",
    ),
    (
        "A second SIGINT or SIGTERM, a hangup or a closed output makes run return 75 and leaves the Job running; nothing but --on-interrupt cancel cancels it.",
        "Ein zweites SIGINT oder SIGTERM, ein Auflegen oder eine geschlossene Ausgabe lässt run mit 75 zurückkehren und den Job weiterlaufen; nur --on-interrupt cancel bricht ihn ab.",
    ),
    (
        "explain why a Job waits, or what a setting of a Queue or Group amounts to",
        "erklären, warum ein Job wartet oder was eine Einstellung einer Queue oder Gruppe bewirkt",
    ),
    (
        "the number of a Job, or the path of a Queue or Group",
        "die Nummer eines Jobs oder der Pfad einer Queue oder Gruppe",
    ),
    (
        "For a path, each setting is shown with the value configured there, the value in effect, the object that supplies it, and why it cannot take effect when an ancestor ceiling, a missing controller or an ancestor bound stands against it.",
        "Für einen Pfad wird jede Einstellung mit dem dort gesetzten Wert, dem wirksamen Wert und dem Objekt gezeigt, das ihn liefert, und mit dem Grund, wenn sie nicht wirken kann, weil eine Obergrenze eines Vorfahren, ein fehlender Controller oder eine Schranke eines Vorfahren dagegen steht.",
    ),
    (
        "limit on the number of processes and threads",
        "Grenze für die Zahl der Prozesse und Threads",
    ),
    (
        "earlier spelling: reserve N processes and threads and limit the Job to them",
        "frühere Schreibweise: N Prozesse und Threads reservieren und den Job darauf begrenzen",
    ),
    (
        "bytes it may write before the service stops it; not a file system quota",
        "Bytes, die er schreiben darf, bevor der Dienst ihn anhält; kein Dateisystemkontingent",
    ),
    (
        "earlier spelling of --write-budget",
        "frühere Schreibweise von --write-budget",
    ),
    (
        "submit --json prints the Job ID as before; --format json wraps the Job record.",
        "submit --json gibt wie bisher die Job-ID aus; --format json umschließt den Job-Datensatz.",
    ),
    (
        "Exit status 1 means that a check failed; the report is printed either way.",
        "Rückgabewert 1 bedeutet, dass eine Prüfung fehlgeschlagen ist; der Bericht wird in jedem Fall ausgegeben.",
    ),
    (
        "--json prints one JSON object per record; --format json prints one envelope whose data holds schema_version, entries and unreadable.",
        "--json gibt ein JSON-Objekt je Eintrag aus; --format json gibt einen Umschlag aus, dessen data schema_version, entries und unreadable enthält.",
    ),
    (
        "--json prints a stream of records, one JSON object per line, and takes no --format json envelope.",
        "--json gibt einen Strom von Einträgen aus, ein JSON-Objekt je Zeile, und nimmt keinen Umschlag von --format json an.",
    ),
    (
        "pass the standard input of this command to the Job and close it at its end",
        "die Standardeingabe dieses Befehls an den Job weitergeben und an ihrem Ende schließen",
    ),
    (
        "one Job, an inclusive range such as 1-10, or a comma list such as 1,4,7-9",
        "ein Job, ein Bereich mit beiden Enden wie 1-10 oder eine Kommaliste wie 1,4,7-9",
    ),
    (
        "With one ID the answer is what it always was. With a range, a list or several operands the service resolves the set in one request and answers one line per Job, or one summary line when more than 20 Jobs behaved the same; --json prints schema_version, kind and one result per ID. IDs inside a range that do not exist are skipped; a missing ID named on its own is reported. A set names at most 10000 IDs.",
        "Mit einer ID ist die Antwort, was sie immer war. Bei einem Bereich, einer Liste oder mehreren Operanden löst der Dienst die Menge in einer Anfrage auf und antwortet mit einer Zeile je Job oder mit einer Sammelzeile, wenn sich mehr als 20 Jobs gleich verhalten haben; --json gibt schema_version, kind und ein Ergebnis je ID aus. IDs in einem Bereich, die es nicht gibt, werden übergangen; eine einzeln genannte ID, die es nicht gibt, wird gemeldet. Eine Menge nennt höchstens 10000 IDs.",
    ),
    (
        "with a set: a Job was refused or failed, an ID named on its own does not exist, or no Job of the set exists",
        "bei einer Menge: ein Job wurde abgelehnt oder schlug fehl, eine einzeln genannte ID gibt es nicht, oder es gibt keinen Job der Menge",
    ),
    (
        "with a set: a change is still pending",
        "bei einer Menge: eine Änderung steht noch aus",
    ),
    (
        "usage error or service failure; with one ID also a refusal",
        "Aufruffehler oder Dienstfehler; bei einer ID auch eine Ablehnung",
    ),
    (
        "With a set, wait waits quietly until every Job of it has ended and prints one line per Job; --timeout bounds the whole wait, and the exit status is the first one in ID order that is not 0, where a Job still running at the deadline counts as 75 and a missing ID named on its own as 1.",
        "Bei einer Menge wartet wait still, bis jeder ihrer Jobs beendet ist, und gibt eine Zeile je Job aus; --timeout begrenzt das ganze Warten, und der Rückgabewert ist der erste in der Reihenfolge der IDs, der nicht 0 ist, wobei ein Job, der zur Frist noch läuft, als 75 zählt und eine einzeln genannte ID, die es nicht gibt, als 1.",
    ),
    (
        "only these Jobs, in every state unless --state says otherwise",
        "nur diese Jobs, in jedem Zustand, wenn --state nichts anderes sagt",
    ),
];

pub fn german() -> bool {
    ["LC_ALL", "LC_MESSAGES", "LANG"]
        .iter()
        .filter_map(|name| std::env::var(name).ok())
        .find(|value| !value.is_empty())
        .unwrap_or_default()
        .starts_with("de")
}

pub fn translated(key: &str) -> bool {
    CATALOGUE.iter().any(|(english, _)| *english == key)
}

pub fn message(key: &str) -> String {
    message_in(german(), key)
}

pub fn message_in(german: bool, key: &str) -> String {
    if german {
        CATALOGUE
            .iter()
            .find(|(english, _)| *english == key)
            .map_or(key, |(_, german)| *german)
            .to_owned()
    } else {
        key.to_owned()
    }
}
