# Generated by `job completion bash` from the shared command definition.
# Change crates/job/src/commands/table.rs, then write this file again.
_job_complete() {
    local cur prev key first count index word opts valued
    cur=${COMP_WORDS[COMP_CWORD]}
    prev=${COMP_WORDS[COMP_CWORD-1]}
    COMPREPLY=()
    for word in "${COMP_WORDS[@]:1:COMP_CWORD-1}"; do
        [[ $word == -- ]] && return
    done
    if (( COMP_CWORD == 1 )); then
        mapfile -t COMPREPLY < <(compgen -W 'run submit create edit release retry wait cancel suspend continue signal update resource-update reprioritize move remove attach list show status explain logs log attempts pressure host metrics screenshot net config state doctor audit events completion help daemon hook classify policy queue group profile class --system' -- "$cur")
        return
    fi
    key=${COMP_WORDS[1]}
    first=2
    if (( COMP_CWORD > 2 )); then
        case "$key ${COMP_WORDS[2]}" in
            'pressure status'|'pressure events'|'pressure replay'|'pressure parse'|'net list'|'net show'|'config check'|'config init'|'config show'|'config reload'|'state validate'|'state backup'|'state migrate'|'state restore'|'queue create'|'queue list'|'queue show'|'queue set'|'queue unset'|'queue rename'|'queue move'|'queue close'|'queue open'|'queue update'|'queue suspend'|'queue continue'|'queue cancel'|'queue remove'|'queue pause'|'queue resume'|'queue add'|'queue clear'|'queue rm'|'group create'|'group list'|'group show'|'group set'|'group unset'|'group rename'|'group move'|'group close'|'group open'|'group update'|'group suspend'|'group continue'|'group cancel'|'group remove'|'group pause'|'group resume'|'profile list'|'profile show'|'class list'|'class show') key="$key ${COMP_WORDS[2]}"; first=3 ;;
        esac
    fi
    opts=
    valued=
    case "$key" in
        'run') opts='--queue --label --idempotency-key --dir --session --shell --legacy-shell --pty --summary --json --budget --time --priority --execution-profile --class --stdin --on-interrupt --cores --mem --pids --write-budget --disk --device --net --net-secret-file --bandwidth --monitor --on --ssh-key --ssh-option --send --fetch --confine --allow-write --cpu-request --memory-request --cpu-limit --cpu-weight --memory-high --memory-max --memory-swap-max --pids-max --io-max --io-weight --io-bfq-weight --cpu-affinity --numa-policy --rlimit --no-new-privs --cap-drop --seccomp-deny --namespaces --root --private-tmp --writable --output-head --output-tail --format --help'; valued='--queue -q --label --idempotency-key --dir --session --shell --budget --time --priority --execution-profile --class --on-interrupt --cores --mem --pids --write-budget --disk --device --net --net-secret-file --bandwidth --monitor --on --ssh-key --ssh-option --send --fetch --allow-write --cpu-request --memory-request --cpu-limit --cpu-weight --memory-high --memory-max --memory-swap-max --pids-max --io-max --io-weight --io-bfq-weight --cpu-affinity --numa-policy --rlimit --no-new-privs --cap-drop --seccomp-deny --namespaces --root --private-tmp --writable --output-head --output-tail --format' ;;
        'submit'|'create'|'edit') opts='--queue --label --idempotency-key --dir --session --shell --legacy-shell --pty --summary --json --budget --time --priority --execution-profile --class --cores --mem --pids --write-budget --disk --device --net --net-secret-file --bandwidth --monitor --on --ssh-key --ssh-option --send --fetch --confine --allow-write --cpu-request --memory-request --cpu-limit --cpu-weight --memory-high --memory-max --memory-swap-max --pids-max --io-max --io-weight --io-bfq-weight --cpu-affinity --numa-policy --rlimit --no-new-privs --cap-drop --seccomp-deny --namespaces --root --private-tmp --writable --output-head --output-tail --format --help'; valued='--queue -q --label --idempotency-key --dir --session --shell --budget --time --priority --execution-profile --class --cores --mem --pids --write-budget --disk --device --net --net-secret-file --bandwidth --monitor --on --ssh-key --ssh-option --send --fetch --allow-write --cpu-request --memory-request --cpu-limit --cpu-weight --memory-high --memory-max --memory-swap-max --pids-max --io-max --io-weight --io-bfq-weight --cpu-affinity --numa-policy --rlimit --no-new-privs --cap-drop --seccomp-deny --namespaces --root --private-tmp --writable --output-head --output-tail --format' ;;
        'release') opts='--dry-run --json --format --help'; valued='--format' ;;
        'retry') opts='--hold --current-env --queue --allow-lost --dry-run --json --format --help'; valued='--queue -q --format' ;;
        'wait') opts='--timeout --summary --json --format --help'; valued='--timeout --format' ;;
        'cancel') opts='--session --dry-run --json --format --help'; valued='--session --format' ;;
        'suspend'|'continue') opts='--timeout --dry-run --json --format --help'; valued='--timeout --format' ;;
        'signal') opts='--signal --dry-run --json --format --help'; valued='--signal -s --format' ;;
        'update'|'queue update'|'group update') opts='--allow-oom --dry-run --json --cpu-limit --cpu-weight --memory-high --memory-max --memory-swap-max --pids-max --io-max --io-weight --io-bfq-weight --format --help'; valued='--cpu-limit --cpu-weight --memory-high --memory-max --memory-swap-max --pids-max --io-max --io-weight --io-bfq-weight --format' ;;
        'resource-update') opts='--abandon --json --format --help'; valued='--format' ;;
        'reprioritize') opts='--priority --dry-run --json --format --help'; valued='--priority --format' ;;
        'move') opts='--queue --dry-run --json --format --help'; valued='--queue -q --format' ;;
        'remove') opts='--dry-run --allow-lost --json --format --help'; valued='--format' ;;
        'attach') opts='--detach-key --help'; valued='--detach-key' ;;
        'list') opts='--all --state --limit --label --queue --id --json --format --help'; valued='--state --limit --label --queue -q --id --format' ;;
        'show'|'status'|'explain'|'attempts'|'pressure'|'pressure status'|'pressure events'|'pressure replay'|'config show'|'queue show'|'queue unset'|'queue rename'|'queue close'|'queue open'|'queue pause'|'queue resume'|'group show'|'group unset'|'group rename'|'group close'|'group open'|'group pause'|'group resume'|'profile'|'profile list'|'profile show'|'class'|'class list'|'class show') opts='--json --format --help'; valued='--format' ;;
        'logs') opts='--follow --stream --attempt --raw --json --since-ms --until-ms --grep --help'; valued='--stream --attempt --since-ms --until-ms --grep' ;;
        'log') opts='--attempt --help'; valued='--attempt' ;;
        'pressure parse') opts='--resource --host --help'; valued='--resource' ;;
        'host') opts='--on --ssh-key --ssh-option --json --format --help'; valued='--on --ssh-key --ssh-option --format' ;;
        'metrics'|'net'|'config'|'config check'|'config reload'|'state'|'completion'|'daemon'|'hook'|'classify'|'queue'|'queue clear'|'group') opts='--help'; valued='' ;;
        'screenshot') opts='--output --job --pid --display --help'; valued='--output -o --job --pid --display' ;;
        'net list'|'net show') opts='--json --help'; valued='' ;;
        'config init') opts='--profile --help'; valued='--profile' ;;
        'state validate') opts='--source --help'; valued='--source' ;;
        'state backup') opts='--source --destination --interrupted --help'; valued='--source --destination' ;;
        'state migrate') opts='--source --destination --backup --profile --dry-run --help'; valued='--source --destination --backup --profile' ;;
        'state restore') opts='--source --destination --help'; valued='--source --destination' ;;
        'doctor') opts='--json --system --format --help'; valued='--format' ;;
        'audit') opts='--target --action --since --json --format --help'; valued='--target --action --since --format' ;;
        'events') opts='--follow --job --queue --since --format --json --help'; valued='--job --queue --since --format' ;;
        'help') opts='--all --syntax --help'; valued='' ;;
        'policy') opts='--show --help'; valued='' ;;
        'queue create'|'group create') opts='--group --json --label --max-running --parallel --cores --mem --dir --net --net-secret-file --pressure --priority --priority-min --priority-max --aging --strict-fifo --backfill --fair-share --share-weight --cpu-limit --cpu-weight --memory-high --memory-max --memory-swap-max --pids-max --io-max --io-weight --io-bfq-weight --job-execution-profile --job-class --job-cpu-request --job-memory-request --job-cpu-limit --job-cpu-weight --job-memory-high --job-memory-max --job-memory-swap-max --job-pids-max --job-io-max --job-io-weight --job-io-bfq-weight --job-cpu-affinity --job-numa-policy --job-rlimit --job-no-new-privs --job-cap-drop --job-seccomp-deny --job-namespaces --job-root --job-private-tmp --job-writable --job-output-head --job-output-tail --format --help'; valued='--group --label --max-running --parallel --cores --mem --dir --net --net-secret-file --pressure --priority --priority-min --priority-max --aging --strict-fifo --backfill --fair-share --share-weight --cpu-limit --cpu-weight --memory-high --memory-max --memory-swap-max --pids-max --io-max --io-weight --io-bfq-weight --job-execution-profile --job-class --job-cpu-request --job-memory-request --job-cpu-limit --job-cpu-weight --job-memory-high --job-memory-max --job-memory-swap-max --job-pids-max --job-io-max --job-io-weight --job-io-bfq-weight --job-cpu-affinity --job-numa-policy --job-rlimit --job-no-new-privs --job-cap-drop --job-seccomp-deny --job-namespaces --job-root --job-private-tmp --job-writable --job-output-head --job-output-tail --format' ;;
        'queue list'|'group list') opts='--label --json --format --help'; valued='--label --format' ;;
        'queue set') opts='--json --label --max-running --parallel --cores --mem --dir --net --net-secret-file --pressure --priority --priority-min --priority-max --aging --strict-fifo --backfill --fair-share --share-weight --cpu-limit --cpu-weight --memory-high --memory-max --memory-swap-max --pids-max --io-max --io-weight --io-bfq-weight --job-execution-profile --job-class --job-cpu-request --job-memory-request --job-cpu-limit --job-cpu-weight --job-memory-high --job-memory-max --job-memory-swap-max --job-pids-max --job-io-max --job-io-weight --job-io-bfq-weight --job-cpu-affinity --job-numa-policy --job-rlimit --job-no-new-privs --job-cap-drop --job-seccomp-deny --job-namespaces --job-root --job-private-tmp --job-writable --job-output-head --job-output-tail --bandwidth --job-bandwidth --on --ssh-key --ssh-option --monitor --host-cores --format --help'; valued='--label --max-running --parallel --cores --mem --dir --net --net-secret-file --pressure --priority --priority-min --priority-max --aging --strict-fifo --backfill --fair-share --share-weight --cpu-limit --cpu-weight --memory-high --memory-max --memory-swap-max --pids-max --io-max --io-weight --io-bfq-weight --job-execution-profile --job-class --job-cpu-request --job-memory-request --job-cpu-limit --job-cpu-weight --job-memory-high --job-memory-max --job-memory-swap-max --job-pids-max --job-io-max --job-io-weight --job-io-bfq-weight --job-cpu-affinity --job-numa-policy --job-rlimit --job-no-new-privs --job-cap-drop --job-seccomp-deny --job-namespaces --job-root --job-private-tmp --job-writable --job-output-head --job-output-tail --bandwidth --job-bandwidth --on --ssh-key --ssh-option --monitor --host-cores --format' ;;
        'queue move'|'group move') opts='--group --json --format --help'; valued='--group --format' ;;
        'queue suspend'|'queue continue'|'group suspend'|'group continue') opts='--recursive --timeout --json --format --help'; valued='--timeout --format' ;;
        'queue cancel'|'group cancel') opts='--recursive --dry-run --json --format --help'; valued='--format' ;;
        'queue remove'|'group remove') opts='--recursive --dry-run --allow-lost --json --format --help'; valued='--format' ;;
        'queue add') opts='--parallel --cores --mem --dir --net --net-secret-file --bandwidth --job-bandwidth --on --ssh-key --ssh-option --monitor --host-cores --help'; valued='--parallel --cores --mem --dir --net --net-secret-file --bandwidth --job-bandwidth --on --ssh-key --ssh-option --monitor --host-cores' ;;
        'queue rm') opts='--when-empty --help'; valued='' ;;
        'group set') opts='--json --label --max-running --parallel --cores --mem --dir --net --net-secret-file --pressure --priority --priority-min --priority-max --aging --strict-fifo --backfill --fair-share --share-weight --cpu-limit --cpu-weight --memory-high --memory-max --memory-swap-max --pids-max --io-max --io-weight --io-bfq-weight --job-execution-profile --job-class --job-cpu-request --job-memory-request --job-cpu-limit --job-cpu-weight --job-memory-high --job-memory-max --job-memory-swap-max --job-pids-max --job-io-max --job-io-weight --job-io-bfq-weight --job-cpu-affinity --job-numa-policy --job-rlimit --job-no-new-privs --job-cap-drop --job-seccomp-deny --job-namespaces --job-root --job-private-tmp --job-writable --job-output-head --job-output-tail --format --help'; valued='--label --max-running --parallel --cores --mem --dir --net --net-secret-file --pressure --priority --priority-min --priority-max --aging --strict-fifo --backfill --fair-share --share-weight --cpu-limit --cpu-weight --memory-high --memory-max --memory-swap-max --pids-max --io-max --io-weight --io-bfq-weight --job-execution-profile --job-class --job-cpu-request --job-memory-request --job-cpu-limit --job-cpu-weight --job-memory-high --job-memory-max --job-memory-swap-max --job-pids-max --job-io-max --job-io-weight --job-io-bfq-weight --job-cpu-affinity --job-numa-policy --job-rlimit --job-no-new-privs --job-cap-drop --job-seccomp-deny --job-namespaces --job-root --job-private-tmp --job-writable --job-output-head --job-output-tail --format' ;;
    esac
    case " $valued " in
        *" $prev "*)
            case "$key:$prev" in
                *:--queue|*:-q) mapfile -t COMPREPLY < <("${COMP_WORDS[0]}" __complete queue "$cur" 2>/dev/null) ;;
                *:--dir|*:--source|*:--destination|*:--backup) mapfile -t COMPREPLY < <(compgen -d -- "$cur") ;;
                *:--shell) mapfile -t COMPREPLY < <(compgen -c -- "$cur") ;;
                *:--budget) mapfile -t COMPREPLY < <(compgen -W 'none' -- "$cur") ;;
                *:--on-interrupt) mapfile -t COMPREPLY < <(compgen -W 'forward detach cancel' -- "$cur") ;;
                *:--net) mapfile -t COMPREPLY < <("${COMP_WORDS[0]}" __complete net "$cur" 2>/dev/null) ;;
                *:--net-secret-file|*:--ssh-key|*:--send|*:--fetch|*:--allow-write|*:--output|*:-o|*:--pressure) mapfile -t COMPREPLY < <(compgen -f -- "$cur") ;;
                *:--cpu-limit|*:--memory-high|*:--memory-max|*:--memory-swap-max|*:--pids-max|*:--max-running|*:--job-cpu-limit|*:--job-memory-high|*:--job-memory-max|*:--job-memory-swap-max|*:--job-pids-max) mapfile -t COMPREPLY < <(compgen -W 'unlimited' -- "$cur") ;;
                *:--cpu-affinity|*:--writable|*:--job-cpu-affinity|*:--job-writable) mapfile -t COMPREPLY < <(compgen -W 'inherit' -- "$cur") ;;
                *:--numa-policy|*:--job-numa-policy) mapfile -t COMPREPLY < <(compgen -W 'inherit default local bind: interleave: preferred:' -- "$cur") ;;
                *:--rlimit|*:--job-rlimit) mapfile -t COMPREPLY < <(compgen -W 'as= core= cpu= data= fsize= memlock= msgqueue= nice= nofile= nproc= rtprio= rttime= sigpending= stack=' -- "$cur") ;;
                *:--no-new-privs|*:--private-tmp|*:--job-no-new-privs|*:--job-private-tmp) mapfile -t COMPREPLY < <(compgen -W 'yes inherit' -- "$cur") ;;
                *:--cap-drop|*:--job-cap-drop) mapfile -t COMPREPLY < <(compgen -W 'all inherit chown dac_override dac_read_search fowner fsetid kill setgid setuid setpcap linux_immutable net_bind_service net_broadcast net_admin net_raw ipc_lock ipc_owner sys_module sys_rawio sys_chroot sys_ptrace sys_pacct sys_admin sys_boot sys_nice sys_resource sys_time sys_tty_config mknod lease audit_write audit_control setfcap mac_override mac_admin syslog wake_alarm block_suspend audit_read perfmon bpf checkpoint_restore' -- "$cur") ;;
                *:--seccomp-deny|*:--job-seccomp-deny) mapfile -t COMPREPLY < <(compgen -W 'inherit getppid getuid getgid uname getcwd ptrace process_vm_readv process_vm_writev kcmp bpf userfaultfd perf_event_open keyctl add_key request_key mount umount2 pivot_root chroot unshare setns clone clone3 socket socketpair connect accept accept4 bind listen sendto recvfrom io_uring_setup io_uring_enter io_uring_register reboot kexec_load init_module finit_module delete_module open_by_handle_at name_to_handle_at sethostname setdomainname syslog acct swapon swapoff fsopen fsconfig fsmount fspick move_mount open_tree mount_setattr kexec_file_load sendmsg recvmsg sendmmsg recvmmsg' -- "$cur") ;;
                *:--namespaces|*:--job-namespaces) mapfile -t COMPREPLY < <(compgen -W 'inherit cgroup ipc mount pid user uts' -- "$cur") ;;
                *:--root|*:--job-root) mapfile -t COMPREPLY < <(compgen -W 'read-only inherit' -- "$cur") ;;
                'run:--format'|'submit:--format'|'create:--format'|'edit:--format'|'release:--format'|'retry:--format'|'wait:--format'|'cancel:--format'|'suspend:--format'|'continue:--format'|'signal:--format'|'update:--format'|'resource-update:--format'|'reprioritize:--format'|'move:--format'|'remove:--format'|'show:--format'|'status:--format'|'explain:--format'|'attempts:--format'|'pressure:--format'|'pressure status:--format'|'pressure events:--format'|'pressure replay:--format'|'host:--format'|'config show:--format'|'doctor:--format'|'audit:--format'|'events:--format'|'queue create:--format'|'queue show:--format'|'queue set:--format'|'queue unset:--format'|'queue rename:--format'|'queue move:--format'|'queue close:--format'|'queue open:--format'|'queue update:--format'|'queue suspend:--format'|'queue continue:--format'|'queue cancel:--format'|'queue remove:--format'|'queue pause:--format'|'queue resume:--format'|'group create:--format'|'group show:--format'|'group set:--format'|'group unset:--format'|'group rename:--format'|'group move:--format'|'group close:--format'|'group open:--format'|'group update:--format'|'group suspend:--format'|'group continue:--format'|'group cancel:--format'|'group remove:--format'|'group pause:--format'|'group resume:--format'|'profile:--format'|'profile list:--format'|'profile show:--format'|'class:--format'|'class list:--format'|'class show:--format') mapfile -t COMPREPLY < <(compgen -W 'text json' -- "$cur") ;;
                *:--signal|*:-s) mapfile -t COMPREPLY < <(compgen -W 'HUP INT QUIT KILL TERM USR1 USR2 STOP CONT TSTP WINCH' -- "$cur") ;;
                *:--detach-key) mapfile -t COMPREPLY < <(compgen -W 'none ctrl-] ctrl-a ctrl-b ctrl-g ctrl-t' -- "$cur") ;;
                *:--state) mapfile -t COMPREPLY < <(compgen -W 'held queued starting running suspended stopping succeeded failed cancelled lost' -- "$cur") ;;
                *:--id|*:--job) mapfile -t COMPREPLY < <("${COMP_WORDS[0]}" __complete job "$cur" 2>/dev/null) ;;
                'list:--format'|'queue list:--format'|'group list:--format') mapfile -t COMPREPLY < <(compgen -W 'text json tsv' -- "$cur") ;;
                *:--stream) mapfile -t COMPREPLY < <(compgen -W 'all stdout stderr combined diagnostic' -- "$cur") ;;
                *:--resource) mapfile -t COMPREPLY < <(compgen -W 'cpu memory io' -- "$cur") ;;
                *:--profile) mapfile -t COMPREPLY < <(compgen -W 'ordinary legacy' -- "$cur") ;;
                *:--group) mapfile -t COMPREPLY < <("${COMP_WORDS[0]}" __complete group "$cur" 2>/dev/null) ;;
                *:--parallel) mapfile -t COMPREPLY < <(compgen -W 'all' -- "$cur") ;;
                *:--strict-fifo) mapfile -t COMPREPLY < <(compgen -W 'true false' -- "$cur") ;;
                *:--backfill) mapfile -t COMPREPLY < <(compgen -W 'off conservative' -- "$cur") ;;
                *:--fair-share) mapfile -t COMPREPLY < <(compgen -W 'off cpu-request-time memory-request-time' -- "$cur") ;;
            esac
            return ;;
    esac
    if [[ $cur == -* ]]; then
        mapfile -t COMPREPLY < <(compgen -W "$opts" -- "$cur")
        return
    fi
    count=0
    index=$first
    while (( index < COMP_CWORD )); do
        word=${COMP_WORDS[index]}
        if [[ $word == -* ]]; then
            case " $valued " in *" $word "*) index=$((index + 1)) ;; esac
        else
            count=$((count + 1))
        fi
        index=$((index + 1))
    done
    case "$key:$count" in
        'edit:0'|'release:0'|'wait:0'|'cancel:0'|'suspend:0'|'continue:0'|'signal:0'|'update:0'|'reprioritize:0'|'move:0'|'attach:0'|'explain:0') mapfile -t COMPREPLY < <("${COMP_WORDS[0]}" __complete job "$cur" 2>/dev/null) ;;
        'retry:0'|'remove:0') mapfile -t COMPREPLY < <("${COMP_WORDS[0]}" __complete ended "$cur" 2>/dev/null) ;;
        'show:0'|'status:0'|'logs:0'|'log:0'|'attempts:0') mapfile -t COMPREPLY < <("${COMP_WORDS[0]}" __complete anyjob "$cur" 2>/dev/null) ;;
        'log:1') mapfile -t COMPREPLY < <(compgen -W 'errors grep lines tail full' -- "$cur") ;;
        'pressure:0') mapfile -t COMPREPLY < <(compgen -W 'status events replay parse' -- "$cur"; "${COMP_WORDS[0]}" __complete job "$cur" 2>/dev/null) ;;
        'pressure replay:0'|'pressure parse:0'|'config check:0'|'config init:0') mapfile -t COMPREPLY < <(compgen -f -- "$cur") ;;
        'net:0'|'profile:0'|'class:0') mapfile -t COMPREPLY < <(compgen -W 'list show' -- "$cur") ;;
        'config:0') mapfile -t COMPREPLY < <(compgen -W 'check init show reload' -- "$cur") ;;
        'state:0') mapfile -t COMPREPLY < <(compgen -W 'validate backup migrate restore' -- "$cur") ;;
        'completion:0') mapfile -t COMPREPLY < <(compgen -W 'bash fish zsh' -- "$cur") ;;
        'queue create:0'|'queue show:0'|'queue set:0'|'queue unset:0'|'queue rename:0'|'queue move:0'|'queue close:0'|'queue open:0'|'queue update:0'|'queue suspend:0'|'queue continue:0'|'queue cancel:0'|'queue remove:0'|'queue pause:0'|'queue resume:0'|'queue add:0'|'queue clear:0'|'queue rm:0') mapfile -t COMPREPLY < <("${COMP_WORDS[0]}" __complete queue "$cur" 2>/dev/null) ;;
        'queue:0') mapfile -t COMPREPLY < <(compgen -W 'create list show set unset rename move close open update suspend continue cancel remove pause resume add clear rm' -- "$cur"; "${COMP_WORDS[0]}" __complete queue "$cur" 2>/dev/null) ;;
        'group create:0'|'group show:0'|'group set:0'|'group unset:0'|'group rename:0'|'group move:0'|'group close:0'|'group open:0'|'group update:0'|'group suspend:0'|'group continue:0'|'group cancel:0'|'group remove:0'|'group pause:0'|'group resume:0') mapfile -t COMPREPLY < <("${COMP_WORDS[0]}" __complete group "$cur" 2>/dev/null) ;;
        'group:0') mapfile -t COMPREPLY < <(compgen -W 'create list show set unset rename move close open update suspend continue cancel remove pause resume' -- "$cur") ;;
        'release:'*|'wait:'*|'cancel:'*|'suspend:'*|'continue:'*|'signal:'*|'reprioritize:'*|'move:'*) mapfile -t COMPREPLY < <("${COMP_WORDS[0]}" __complete job "$cur" 2>/dev/null) ;;
        'retry:'*|'remove:'*) mapfile -t COMPREPLY < <("${COMP_WORDS[0]}" __complete ended "$cur" 2>/dev/null) ;;
        'log:'*) mapfile -t COMPREPLY < <(compgen -W 'errors grep lines tail full' -- "$cur") ;;
    esac
}
complete -o default -o bashdefault -F _job_complete job
